version: '3'
services:
	web: 
		image: docker-node-express-mongoapp
		restart: always
		build: .
		ports:
			- '80:9000'
		depends_on:
			- "mongo"
	links:
		- mongo
	mongo:
		container_name: mongo
		image: "mongo"
		ports:
			- '27017:27017'

